version: "3.3"
services:
  db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=holo
          - MYSQL_DATABASE=under_society_db
  web:
      image: dawpractica21/springboot:springboot
      ports:
      - "8443:8443"
      restart: always
      volumes:
      - .:/usr/app
      depends_on:
      - db