web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/usr/app
    links:
    - db
db:
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=holo
        - MYSQL_DATABASE=under_society_db