web:
    build: .
    ports:
    - "8443:8443"
    volumes:
    - .:/usr/app
    links:
    - db
db:
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=holo
        - MYSQL_DATABASE=under_society_db
